Codeinwp/wp-product-review

css/frontpage.css, inc/wppr-filters.php, inc/wppr-main.php, javascript/main.js, readme.txt, wp-product-review.php
Added filters for review name, pros/cons and options
=> Fixed review image styling problem

css/cwppos-widget.css, css/frontpage.css, inc/wppr-main.php, readme.txt, wp-product-review.php
Fixed border customization bug for review box
=> Fixed responsive design bug

inc/wppr-main.php, readme.txt, wp-product-review.php
Fixed rating problem on some instalation when display the numerator greater than denominator
Added wppr_review_image_size for filter the image size;
=> Fixed some design issues.

inc/cwp_metabox.php, inc/wppr-filters.php, inc/wppr-main.php, javascript/cwp-pointers.js
comments in https://github.com/Codeinwp/wp-product-review/pull/123
=> amazon upsell link #121

assets/css/editor.css, includes/admin/class-wppr-editor.php, includes/admin/layouts/editor-default-tpl.php, tests/test-core.php
Added the text as specified. @selul @contactashish13 do check! and do we need to create a doc as well?
=> Added text as specified in issue #136 

includes/admin/class-wppr-admin.php, includes/admin/class-wppr-global-settings.php, includes/admin/layouts/settings-tpl.php, includes/class-wppr.php
https://github.com/Codeinwp/wp-product-review-pro/issues/98
=> display shortcode prominently and link to documentation

includes/admin/controllers/class-wppr-admin-render-controller.php, includes/public/layouts/default.php
@rodica-andronache I also noticed that we are not showing prices on the two Pro templates
=> fixed default template price formatting

CHANGELOG.md, includes/admin/class-wppr-admin.php, includes/admin/widgets/abstract/class-wppr-widget-abstract.php, includes/class-wppr.php, readme.md, readme.txt, themeisle-hash.json
=> Custom image size for widget #292

includes/functions.php, phpcs.xml
=> Template 2 shows empty stars (with a PHP notice if debug is enabled)

includes/functions.php
=> Star rating shows only 4 stars when rating is 4/5 (should show 4 stars + 1 empty star)

.travis.yml, includes/class-wppr.php, phpcs.xml
=> Review categories not working

dist/includes/admin/class-wppr-admin.php, dist/includes/admin/class-wppr-editor.php, dist/includes/admin/class-wppr-global-settings.php, dist/includes/admin/models/class-wppr-query-model.php, dist/includes/admin/widgets/abstract/class-wppr-widget-abstract.php, dist/includes/admin/widgets/class-wppr-latest-products-widget.php, dist/includes/admin/widgets/class-wppr-top-products-widget.php, dist/includes/class-wppr.php, dist/includes/gutenberg/class-wppr-gutenberg.php, dist/includes/legacy.php, dist/includes/public/class-wppr-public.php, dist/includes/public/layouts/default.php, includes/admin/class-wppr-admin.php, includes/admin/class-wppr-editor.php, includes/admin/class-wppr-global-settings.php, includes/admin/models/class-wppr-query-model.php, includes/admin/widgets/abstract/class-wppr-widget-abstract.php, includes/admin/widgets/class-wppr-latest-products-widget.php, includes/admin/widgets/class-wppr-top-products-widget.php, includes/class-wppr.php, includes/gutenberg/class-wppr-gutenberg.php, includes/legacy.php, includes/public/class-wppr-public.php, includes/public/layouts/default.php
https://github.com/Codeinwp/wp-product-review/issues/315
=> Extend abilities of review post type #315

includes/public/layouts/style1.php
=> Style 1 main rating should always be stars and not custom icon

wp-product-review.php
=> User Feedback - change include file method

includes/admin/models/class-wppr-query-model.php, includes/admin/models/class-wppr-review-model.php
=> limit decimal points when user influence is on

includes/admin/models/class-wppr-review-model.php
=> Add filter to change schema information

includes/class-wppr.php
=> Top/Latest Products widget: custom taxonomies do not populate

includes/admin/models/class-wppr-query-model.php, includes/admin/models/class-wppr-review-model.php
=> limit decimal points when user influence is on 

includes/public/layouts/default.php, includes/public/layouts/style1.php, includes/public/layouts/style2.php, includes/public/layouts/widget/style 1.php
=> Outgoing Links doesn´t have “noopener”

assets/js/main.js, includes/public/class-wppr-public.php
=> Review comments slider does not support RTL

assets/js/widget-admin.js
=> Top Reviews widget: JS error while changing post type

assets/js/admin-review.js
=> JS error in non-review type posts

includes/admin/class-wppr-global-settings.php
=> Manually placed option for review box should only show when pro enabled

includes/admin/class-wppr-global-settings.php
=> "manually placed" should show up only for pro; other options should show all the time

includes/admin/models/class-wppr-review-model.php
=> populate schema even when user review is not enabled

includes/admin/models/class-wppr-review-model.php
https://github.com/Codeinwp/wp-product-review-pro/issues/195
=> Schema error: Unspecified Type (The @type is required and cannot be an empty string.)

includes/admin/helpers/class-wppr-html-fields.php
=> Number of options/pros/cons goes back to default (3) after being set

.travis.yml
=> Travis builds for PHP below 5.6 fail with latest WP

includes/admin/class-wppr-admin.php
https://github.com/Codeinwp/wp-product-review/issues/423
=> While creating posts, the schema accordion does not appear.

includes/public/class-wppr-public.php
=> Add filter to disable comments per review

includes/admin/models/class-wppr-schema-model.php
=> Add ability to add schema types without deleting the cache

includes/admin/helpers/class-wppr-html-fields.php
https://github.com/Codeinwp/wp-product-review-pro/issues/198
=> Ability to add product description

assets/css/circle.css, assets/css/default.css, assets/css/rating-amp.css, includes/admin/class-wppr-admin.php, includes/functions.php, includes/public/class-wppr-public.php
=> Improve UI for AMP requests

assets/css/default.css, includes/public/layouts/style2.php
=> Conflict with themes that use CSS class clearfix

includes/admin/class-wppr-admin.php
#433  (ignore the name of the branch on clone)
=> Make rating column sortable in listing screen

includes/admin/models/class-wppr-query-model.php
=> When limited number of rows are being show and user influence is on, sort by comment rating

includes/public/class-wppr-public.php
=> External CSS not allowed in AMP

readme.md, readme.txt, wp-product-review.php
=> Test with WP 5.3

CHANGELOG.md, includes/admin/helpers/class-wppr-html-fields.php, includes/admin/layouts/editor-default-tpl.php, includes/admin/layouts/header-part.php, includes/admin/layouts/settings-tpl.php, includes/admin/layouts/support-tpl.php, readme.md, readme.txt, themeisle-hash.json
https://github.com/Codeinwp/wp-product-review-pro/issues/219
=> remove pro mentions in the free library

readme.md, readme.txt
https://github.com/Codeinwp/wp-product-review-pro/issues/219#event-3002319225
=> remove PRO mentions from readme

CHANGELOG.md, readme.md, readme.txt, themeisle-hash.json, wpml-config.xml
=> Pros and Cons text headings do not show up in polylang

CHANGELOG.md, assets/css/comments.css, includes/public/layouts/comment-rating-star-tpl.php, readme.md, readme.txt, themeisle-hash.json
=> Comment review appears weird on TwentyTwenty theme

CHANGELOG.md, includes/admin/class-wppr-admin.php, includes/class-wppr-activator.php, includes/class-wppr.php, readme.md, readme.txt, themeisle-hash.json
=> bulk activation of plugin aborts activation of subsequent plugins

CHANGELOG.md, includes/public/layouts/widget/default.php, readme.md, readme.txt, themeisle-hash.json
=> Widget: Thumbnail should also link to the review

CHANGELOG.md, includes/functions.php, includes/gutenberg/class-wppr-gutenberg.php, readme.md, readme.txt, themeisle-hash.json
=> check permission and sanitize output

CHANGELOG.md, includes/admin/class-wppr-admin.php, includes/admin/models/class-wppr-editor-model.php, includes/class-wppr.php, package.json, readme.md, readme.txt, themeisle-hash.json, wp-product-review.php
sanitize fields and use local css
=> Issue vul wporg

CHANGELOG.md, includes/admin/class-wppr-admin.php, includes/admin/layouts/editor-default-tpl.php, includes/admin/layouts/settings-tpl.php, includes/class-wppr.php, includes/functions.php, includes/public/layouts/comment-rating-slider-tpl.php, includes/public/layouts/comment-rating-star-tpl.php, includes/public/layouts/default.php, includes/public/layouts/style1.php, package.json, readme.md, readme.txt, themeisle-hash.json, wp-product-review.php
=> sanitize values

CHANGELOG.md, includes/public/class-wppr-public.php, readme.md, readme.txt, themeisle-hash.json
=> Plugin shows entire review in the content even in the sidebar

includes/gutenberg/class-wppr-gutenberg.php
https://github.com/Codeinwp/wp-product-review-pro/issues/226
=> add permission_callback
